import type { CrmData } from "./types";

export const STORAGE_KEY = "axion-gutachten-crm-v1";

export const seedData: CrmData = {
  customers: [
    {
      id: "cust_001",
      name: "Julia Neumann",
      email: "julia.neumann@email.de",
      phone: "+49 170 4455667",
      address: "Bergstraße 18, 80331 München",
      notes: "Unfallgeschädigte – Haftpflichtgegner",
      createdAt: "2025-11-12",
    },
    {
      id: "cust_002",
      name: "Karo Flotte GmbH",
      email: "fuhrpark@karo-flotte.de",
      phone: "+49 89 778899",
      address: "Gewerbepark 4, 85748 Garching",
      notes: "Firmenkunde – Zustandsberichte",
      createdAt: "2025-06-01",
    },
    {
      id: "cust_003",
      name: "Markus Brandt",
      email: "m.brandt@web.de",
      phone: "+49 176 1122334",
      address: "Lindenweg 7, 82131 Gauting",
      notes: "Oldtimer-Interessent",
      createdAt: "2026-01-20",
    },
    {
      id: "cust_004",
      name: "Sara Yilmaz",
      email: "sara.yilmaz@mail.de",
      phone: "+49 151 9988776",
      address: "Isarstraße 55, 81541 München",
      notes: "",
      createdAt: "2026-07-02",
    },
  ],
  vehicles: [
    {
      id: "veh_001",
      customerId: "cust_001",
      make: "Audi",
      model: "A4 Avant",
      year: 2021,
      plate: "M-JN 441",
      vin: "WAUZZZF45NN123456",
      mileage: 52400,
    },
    {
      id: "veh_002",
      customerId: "cust_002",
      make: "Volkswagen",
      model: "Transporter T6.1",
      year: 2020,
      plate: "M-KF 12",
      vin: "WV2ZZZ7HZLH123456",
      mileage: 118000,
    },
    {
      id: "veh_003",
      customerId: "cust_002",
      make: "Mercedes-Benz",
      model: "Vito",
      year: 2019,
      plate: "M-KF 13",
      vin: "WDF4476031N123456",
      mileage: 142500,
    },
    {
      id: "veh_004",
      customerId: "cust_003",
      make: "Porsche",
      model: "911 Carrera 3.2",
      year: 1987,
      plate: "M-MB 911",
      vin: "WP0ZZZ91ZHS123456",
      mileage: 98400,
    },
    {
      id: "veh_005",
      customerId: "cust_004",
      make: "BMW",
      model: "320d",
      year: 2022,
      plate: "M-SY 320",
      vin: "WBA8E9C50NK123789",
      mileage: 28900,
    },
  ],
  appointments: [
    {
      id: "apt_001",
      customerId: "cust_001",
      vehicleId: "veh_001",
      date: "2026-08-05",
      time: "10:00",
      service: "Unfall-Schadengutachten",
      location: "Vor Ort · München Bergstraße",
      status: "bestätigt",
      notes: "Heckschaden nach Auffahrunfall",
    },
    {
      id: "apt_002",
      customerId: "cust_004",
      vehicleId: "veh_005",
      date: "2026-08-06",
      time: "14:30",
      service: "Schadengutachten",
      location: "Werkstatt Partner Süd",
      status: "geplant",
      notes: "Parkschaden Beifahrertür",
    },
    {
      id: "apt_003",
      customerId: "cust_003",
      vehicleId: "veh_004",
      date: "2026-08-08",
      time: "09:00",
      service: "Oldtimer-Wertgutachten",
      location: "Vor Ort · Gauting",
      status: "geplant",
      notes: "Verkaufsvorbereitung",
    },
    {
      id: "apt_004",
      customerId: "cust_002",
      vehicleId: "veh_002",
      date: "2026-08-07",
      time: "08:30",
      service: "Zustandsbericht",
      location: "Fuhrpark Garching",
      status: "bestätigt",
      notes: "Leasingrückgabe Q3",
    },
  ],
  cases: [
    {
      id: "case_001",
      customerId: "cust_001",
      vehicleId: "veh_001",
      type: "Unfall-Schadengutachten",
      title: "Auffahrunfall A4 Avant",
      description: "Heckschaden, Stoßfänger und Heckklappe betroffen",
      status: "in-arbeit",
      insurance: "Allianz Versicherung",
      claimNumber: "AZ-2026-88421",
      estimatedFee: 650,
      actualFee: 0,
      startedAt: "2026-08-04",
      completedAt: null,
    },
    {
      id: "case_002",
      customerId: "cust_002",
      vehicleId: "veh_003",
      type: "Zustandsbericht",
      title: "Leasingrückgabe Vito",
      description: "Vollständiger Zustandsbericht für Leasinggeber",
      status: "fertig",
      insurance: "",
      claimNumber: "",
      estimatedFee: 320,
      actualFee: 320,
      startedAt: "2026-07-20",
      completedAt: "2026-07-22",
    },
    {
      id: "case_003",
      customerId: "cust_004",
      vehicleId: "veh_005",
      type: "Schadengutachten",
      title: "Parkschaden BMW 320d",
      description: "Seitenschaden Beifahrertür und Schweller",
      status: "terminiert",
      insurance: "HUK-Coburg",
      claimNumber: "HUK-99102",
      estimatedFee: 480,
      actualFee: 0,
      startedAt: "2026-08-06",
      completedAt: null,
    },
    {
      id: "case_004",
      customerId: "cust_003",
      vehicleId: "veh_004",
      type: "Oldtimer-Wertgutachten",
      title: "Wertgutachten Porsche 911",
      description: "Marktwertermittlung inkl. Originalitätsprüfung",
      status: "neu",
      insurance: "",
      claimNumber: "",
      estimatedFee: 890,
      actualFee: 0,
      startedAt: "2026-08-08",
      completedAt: null,
    },
  ],
  leads: [
    {
      id: "lead_001",
      name: "Tobias Klein",
      email: "t.klein@email.de",
      phone: "+49 162 3344556",
      gutachtenType: "Unfall-Schadengutachten",
      message: "Gestern Unfall auf der A9, bitte kurzfristig Termin.",
      vehicleInfo: "VW Golf VIII, M-TK 90",
      status: "neu",
      createdAt: "2026-08-04",
      convertedCustomerId: null,
    },
    {
      id: "lead_002",
      name: "Elena Vogt",
      email: "elena.vogt@mail.de",
      phone: "+49 175 6677889",
      gutachtenType: "Wertgutachten",
      message: "Möchte meinen Occasionswagen vor dem Verkauf bewerten lassen.",
      vehicleInfo: "Mercedes C-Klasse 2019",
      status: "kontaktiert",
      createdAt: "2026-08-02",
      convertedCustomerId: null,
    },
  ],
};
